const data = [
  {
    _id: '1',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/controller.png?raw=true',
    name: 'HAVIT HV G-92 Gamepad',
    description:'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
    price: '$120',
    rating: 4.5,
    category: 'Electronics',
    countInStock: 4,
    numReviews:23,
    stock: 234,
  },
  {
    _id: '2',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/keybord.png?raw=true',
    name: 'AK-900 Wired Keyboard',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    price: '$300',
    rating: 4,
    category: 'Electronics',
    countInStock: 6,
    numReviews:6,
    stock: 1,
  },
  {
    _id: '3',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/monitor.png?raw=true',
    name: 'IPS LCD Gaming Monitor',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    price: '$890',
    rating: 4.5,
    category: 'Electronics',
    countInStock: 6,
    numReviews:6,
    stock: 1,
  },

  {
    _id: '4',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/Chiar.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'S-Series Comforte Chair',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    category: 'home',
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
]

export default data