const data = [
  {
    _id: '1',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/controller.png?raw=true',
    image2: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/image%2063.png?raw=true',
    image3: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/image%2061.png?raw=true',
    image4: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/image%2059.png?raw=true',
    image5: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/image%2058.png?raw=true',
    image6: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/image%2057.png?raw=true',
    name: 'HAVIT HV G-92 Gamepad',
    description:'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
    price: '$120',
    rating: 4.5,
    category: 'Electronics',
    countInStock: 4,
    numReviews:8,
  },
  {
    _id: '2',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/keybord.png?raw=true',
    name: 'AK-900 Wired Keyboard',
    price: '$300',
    rating: 4,
    category: 'Electronics',
    countInStock: 6,
    numReviews:6,
  },
  {
    _id: '3',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/monitor.png?raw=true',
    name: 'IPS LCD Gaming Monitor',
    price: '$890',
    rating: 4.5,
    category: 'Electronics',
    countInStock: 6,
    numReviews:6,
  },

  {
    _id: '4',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/Chiar.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'S-Series Comforte Chair',
    price: '$890',
    rating: 4,
    category: 'home',
    countInStock: 8,
    numReviews: 9,
  },
]

export default data